# Generated by Django 6.0.1 on 2026-02-06 16:24

import core.models.book_copy
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=17)),
                ('bbc', models.CharField(max_length=30)),
                ('published_city', models.CharField(max_length=50)),
                ('published_year', models.IntegerField()),
                ('pages', models.IntegerField(default=0)),
                ('image', models.CharField(default='book_default.jpg', max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookCopyCondition',
            fields=[
                ('condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.CharField(null=True, unique=True, verbose_name=30)),
            ],
            options={
                'db_table': 'bookcopycondition',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('date_time', models.CharField(max_length=40)),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('reader_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=30, null=True, unique=True)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('place_of_study', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'reader',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('bookcopy_id', models.AutoField(primary_key=True, serialize=False)),
                ('copy_number', models.IntegerField(default=core.models.book_copy.get_next_number, unique=True)),
                ('is_available', models.BooleanField()),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('condition', models.ForeignKey(db_column='condition_id', on_delete=django.db.models.deletion.CASCADE, to='core.bookcopycondition')),
            ],
            options={
                'db_table': 'bookcopy',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, to='core.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(db_column='publisher_id', on_delete=django.db.models.deletion.CASCADE, to='core.publisher'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, db_column='role', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('return_date', models.DateField()),
                ('book_copy', models.ForeignKey(db_column='bookcopy_id', on_delete=django.db.models.deletion.CASCADE, to='core.bookcopy')),
                ('reader', models.ForeignKey(db_column='reader_id', on_delete=django.db.models.deletion.CASCADE, to='core.reader')),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
            options={
                'db_table': 'loan',
            },
        ),
    ]
