# Generated by Django 6.0.1 on 2026-02-06 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='book_copy',
            field=models.ForeignKey(db_column='bookcopy_id', on_delete=django.db.models.deletion.CASCADE, to='core.bookcopy', verbose_name='Номер экземпляра'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(verbose_name='Дата к которой нужно вернуть книгу'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='issue_date',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='reader',
            field=models.ForeignKey(db_column='reader_id', on_delete=django.db.models.deletion.CASCADE, to='core.reader', verbose_name='Читатель'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата возврата'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, to='core.status', verbose_name='Статус'),
        ),
    ]
